version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: voting_system
      POSTGRES_USER: voting_user
      POSTGRES_PASSWORD: voting_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - voting_network

  # Redis (optional, for session storage)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - voting_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://voting_user:voting_password@postgres/voting_system
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - ENVIRONMENT=production
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - voting_network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - voting_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  voting_network:
    driver: bridge 